services:
  backend:
    build:
      context: ./backend
    ports:
      - "3333:3333"
    #! WE SHOULD NEVER USE HARDCODED ENV VARS, THIS IS FOR DEMO ONLY
    environment:
      - TZ=UTC
      - PORT=3333
      - LOG_LEVEL=info
      - APP_KEY=v1GqV_J6iFq64NPhO5tW-aYeDMg0kaXM
      - NODE_ENV=production
    networks:
      - weather-forecast-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    #! WE SHOULD NEVER USE HARDCODED ENV VARS, THIS IS FOR DEMO ONLY
    environment:
      - NEXT_PUBLIC_BACKEND_BASE_URL=http://localhost:3333
    networks:
      - weather-forecast-network
    depends_on:
      - backend

networks:
  weather-forecast-network:
    driver: bridge
