services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    #! WE SHOULD NEVER USE HARDCODED ENV VARS, THIS IS FOR DEMO ONLY
    environment:
      - NEXT_PUBLIC_BACKEND_BASE_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    #! WE SHOULD NEVER USE HARDCODED ENV VARS, THIS IS FOR DEMO ONLY
    environment:
      - TZ=UTC
      - PORT=8000
      - HOST=localhost
      - LOG_LEVEL=info
      - APP_KEY=v1GqV_J6iFq64NPhO5tW-aYeDMg0kaXM
      - NODE_ENV=production

networks:
  weather-forecast-network:
    driver: bridge
