# fly.toml app configuration file generated for weather-backend on 2024-11-18T11:40:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weather-backend'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[env]
  TZ="UTC"
  PORT="80"
  HOST="localhost"
  LOG_LEVEL="info"
  APP_KEY="v1GqV_J6iFq64NPhO5tW-aYeDMg0kaXM"
  NODE_ENV="production"